#!/usr/bin/env python

"""minipkg.py - install pkgsrc

Usage: python minipkg.py [-h | --help] [-v | --version]
"""


from __future__ import print_function
import os
import subprocess
import sys
import urllib2


__author__ = 'Mansour Moufid'
__copyright__ = 'Copyright 2015, Mansour Moufid'
__email__ = 'mansourmoufid@gmail.com'
__license__ = 'ISC'
__status__ = 'Development'
__version__ = '0.4'


supported_sys = ('Linux', 'Darwin')

supported_mach = {
    'i386': '32',
    'x86_64': '64',
}

default_compiler = {
    'Linux': 'gcc',
    'Darwin': 'clang',
}

archive = 'http://minipkg.eliteraspberries.com/pkgsrc-2015Q3.tar.gz'


def uname():
    p = subprocess.Popen(['uname', '-sm'], stdout=subprocess.PIPE)
    p.wait()
    assert p.returncode == 0, 'uname'
    (sys, mach) = p.stdout.read().split()
    return (sys, mach)


def fetch(url):
    filename = os.path.basename(url)
    if not os.path.exists(filename):
        req = urllib2.Request(url)
        res = urllib2.urlopen(req)
        dat = res.read()
        with open(filename, 'wb') as f:
            f.write(dat)
    return filename


if __name__ == '__main__':

    assert len(sys.argv) in (1, 2)
    if len(sys.argv) == 1:
        pass
    elif len(sys.argv) == 2:
        if sys.argv[1] in ('-h', '--help'):
            print(__doc__)
            sys.exit(os.EX_OK)
        elif sys.argv[1] in ('-v', '--version'):
            print('minipkg version', __version__)
            sys.exit(os.EX_OK)
        else:
            print(__doc__)
            sys.exit(os.EX_USAGE)

    # Step 1:
    # Determine some information about the machine.
    HOME = os.environ['HOME']
    sys, mach = uname()
    assert sys in supported_sys, 'unsupported system'
    assert mach in supported_mach, 'unsupported architecture'
    OPSYS = sys
    ABI = supported_mach[mach]
    CC = os.environ.get('CC', None) or default_compiler[OPSYS]
    print('minipkg: HOME:', HOME)
    print('minipkg: OPSYS:', OPSYS)
    print('minipkg: ABI:', ABI)
    print('minipkg: CC:', CC)

    # Step 2:
    # Fetch the pkgsrc archive.
    print('minipkg: fetching', archive, '...')
    tgz = fetch(archive)

    # Step 3:
    # Extract the pkgsrc archive.
    print('minipkg: extracting', tgz, '...')
    home_usr = os.path.join(HOME, 'usr')
    if not os.path.exists(home_usr):
        os.mkdir(home_usr)
        tar = tgz.rstrip('.gz')
        if not os.path.exists(tar):
            err = subprocess.call(['gunzip', tgz])
            assert err == 0, 'gunzip'
        err = subprocess.call(['tar', '-xf', tar, '-C', home_usr])
        assert err == 0, 'tar'

    # Step 4:
    # Bootstrap pkgsrc.
    print('minipkg: bootstrapping ...')
    sh = os.environ.get('SH', '/bin/bash')
    sh = sh.split(os.pathsep)[0]
    assert os.path.exists(sh), sh
    os.putenv('SH', sh)
    bootstrap_path = os.path.join(HOME, 'usr', 'pkgsrc', 'bootstrap')
    if not os.path.exists(os.path.join(bootstrap_path, 'work')):
        os.chdir(bootstrap_path)
        log = os.path.join(HOME, 'pkgsrc-bootstrap-log.txt')
        with open(log, 'w') as f:
            p = subprocess.Popen(
                [
                    './bootstrap',
                    '--unprivileged',
                    '--abi', ABI,
                    '--compiler', CC,
                    '--make-jobs', '4',
                ],
                stdout=f,
                stderr=f,
            )
            p.wait()
        assert p.returncode == 0, 'bootstrap'

    # Step 5:
    # Set environment variables.
    print('minipkg: setting environment variables ...')
    vars = [
        ('PATH', '$HOME/pkg/bin'),
        ('PATH', '$HOME/pkg/sbin'),
        ('MANPATH', '$HOME/pkg/man'),
    ]
    script = [
        'export %s="%s:$%s"' % (key, val, key)
        for (key, val) in vars
    ]
    profile = os.path.join(HOME, '.bash_profile')
    with open(profile, 'a') as f:
        print('# generated by minipkg', file=f)
        for line in script:
            print(line, file=f)
        print('export SH=%s' % sh, file=f)
    with open(os.path.join(HOME, '.bashrc'), 'a') as f:
        print('. ~/.bash_profile', file=f)

    print('minipkg: done!')
